### ISSUE TITLE
Fiddler Script Failed to Save ResponseBody.txt

### ISSUE THREAD

**Issue by Sduby22** [lNeverl/cidaren#1]
static function OnBeforeResponse(oSession: Session) {
        if(oSession.uriContains("https://wap.vocabgo.com/Student/ClassTask/SubmitAnswer")){
            oSession.utilDecodeResponse();
            oSession.SaveResponse("c:/cdr/response.txt",true);
            oSession.SaveResponseBody("c:cdr/responseBody.txt");
        }
        if(oSession.uriContains("https://wap.vocabgo.com/Student/StudyTask/SubmitAnswer")){
            oSession.utilDecodeResponse();
            oSession.SaveResponse("c:cdr/response.txt",true);
            oSession.SaveResponseBody("c:cdr/responseBody.txt");
        }

如果把`c:cdr`改成`c:/cdr`就可以正常保存了，不知道是不是我自己的问题

**Comment by lNeverl** [comment]
已经更改  是我的疏忽
